name: pizza_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  bloc: ^9.2.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  font_awesome_flutter: ^10.12.0
  
  user_repository:
    path: packages/user_repository
  pizza_repository:
    path: packages/pizza_repository

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - assets/